spring:
  application:
    name: Assicurazioni

  datasource:
    url: jdbc:oracle:thin:@192.168.1.32:1521:XE
    username: ANAGRAFICA
    password: ANAGRAFICA

  jpa:
    show-sql: true

logging:
  file:
    name: logs/app.log
  level:
    root: INFO
