spring:
  application:
    name: Assicurazioni

  datasource:
    url: jdbc:oracle:thin:@192.168.1.32:1521:XE
    username: ANAGRAFICA
    password: ANAGRAFICA

  jpa:
    show-sql: true

logging:
  file:
    name: logs/app.log
  level:
    root: INFO
    org.hibernate.SQL: DEBUG

security:
  user:
    name: "admin"
    password: "rufini"
    role: "USER"