CREATE TABLE COSTO_POLIZZA_REGIONE(
    ID_REGIONE NUMBER NOT NULL,
    INCREMENTO NUMBER NOT NULL,
    DT_INIZIO DATE NOT NULL,
    DT_FINE DATE,
    PRIMARY KEY(ID_REGIONE, DT_INIZIO)
);

COMMENT ON COLUMN COSTO_POLIZZA_REGIONE.ID_REGIONE IS 'identificativo della classe associata e prima parte della chiave primaria';
COMMENT ON COLUMN COSTO_POLIZZA_REGIONE.INCREMENTO IS 'incremento in percentuale';
COMMENT ON COLUMN COSTO_POLIZZA_REGIONE.DT_INIZIO IS 'data inizio validità e seconda parte della chiave primaria';
COMMENT ON COLUMN COSTO_POLIZZA_REGIONE.DT_FINE IS 'data fine validità';

