CREATE TABLE COSTO_POLIZZA_CLASSE(
    ID_CLASSE NUMBER NOT NULL,
    INCREMENTO NUMBER NOT NULL,
    DT_INIZIO DATE NOT NULL,
    DT_FINE DATE,
    PRIMARY KEY(ID_CLASSE, DT_INIZIO)
);

ALTER TABLE COSTO_POLIZZA_CLASSE ADD CONSTRAINT FK_CLASSE_COSTO FOREIGN KEY(ID_CLASSE) REFERENCES CLASSE(ID_CLASSE);

COMMENT ON COLUMN COSTO_POLIZZA_CLASSE.ID_CLASSE IS 'identificativo della classe associata e prima parte della chiave primaria';
COMMENT ON COLUMN COSTO_POLIZZA_CLASSE.INCREMENTO IS 'incremento in percentuale';
COMMENT ON COLUMN COSTO_POLIZZA_CLASSE.DT_INIZIO IS 'data inizio validità e seconda parte della chiave primaria';
COMMENT ON COLUMN COSTO_POLIZZA_CLASSE.DT_FINE IS 'data fine validità';