CREATE TABLE DOCUMENTO_POLIZZA (
    ID NUMBER NOT NULL,
    ID_POLIZZA NUMBER NOT NULL,
    DOC BLOB NOT NULL,
    NOME_FILE VARCHAR2(128) NOT NULL,
    DT_INSERT TIMESTAMP NOT NULL,
    UTENTE_C VARCHAR2(16) NOT NULL,
    PRIMARY KEY(ID, DT_INSERT)
);