CREATE TABLE POLIZZA (
    ID_POLIZZA NUMBER NOT NULL, --identificativo polizza
    DT_INSERIMENTO DATE NOT NULL, --data inserimento
    ID_TIPO_POLIZZA NUMBER NOT NULL,    --identificativo tipo polizza
    ID_CLASSE NUMBER NOT NULL,  --identificativo classe polizza
    ID_INTESTATARIO NUMBER NOT NULL,    --identificativo intestatario polizza
    ID_STATO_POLIZZA NUMBER NOT NULL,   --identificativo stato polizza
    NUM_POLIZZA VARCHAR2(64) NOT NULL,  --numero della polizza
    DT_INIZIO DATE NOT NULL,    --data inizio polizza
    DT_FINE DATE NOT NULL,  --data fine polizza
    NOTE VARCHAR2(255)  --note polizza
);

ALTER TABLE POLIZZA ADD UTENTE_C VARCHAR2(16);

COMMENT ON COLUMN POLIZZA.ID_POLIZZA IS 'identificativo polizza';
COMMENT ON COLUMN POLIZZA.DT_INSERIMENTO IS 'data inserimento';
COMMENT ON COLUMN POLIZZA.ID_TIPO_POLIZZA IS 'identificativo tipo polizza';
COMMENT ON COLUMN POLIZZA.ID_CLASSE IS 'identificativo classe polizza';
COMMENT ON COLUMN POLIZZA.ID_INTESTATARIO IS 'identificativo intestatario polizza';
COMMENT ON COLUMN POLIZZA.ID_STATO_POLIZZA IS 'identificativo stato polizza';
COMMENT ON COLUMN POLIZZA.NUM_POLIZZA IS 'numero della polizza';
COMMENT ON COLUMN POLIZZA.DT_INIZIO IS 'data inizio polizza';
COMMENT ON COLUMN POLIZZA.DT_FINE IS 'data fine polizza';
COMMENT ON COLUMN POLIZZA.NOTE IS 'note polizza';
COMMENT ON COLUMN POLIZZA.UTENTE_C IS 'codice fiscale di utente';

ALTER TABLE POLIZZA ADD CONSTRAINT ID_DT_POLIZZA PRIMARY KEY (ID_POLIZZA, DT_INSERIMENTO);
ALTER TABLE POLIZZA ADD CONSTRAINT FK_TIPO_POLIZZA FOREIGN KEY(ID_TIPO_POLIZZA) REFERENCES TIPO_POLIZZA(ID_TIPO_POLIZZA);
ALTER TABLE POLIZZA ADD CONSTRAINT FK_CLASSE FOREIGN KEY(ID_CLASSE) REFERENCES CLASSE(ID_CLASSE);
ALTER TABLE POLIZZA ADD CONSTRAINT FK_STATO_POLIZZA FOREIGN KEY (ID_STATO_POLIZZA) REFERENCES STATO_POLIZZA(ID_STATO_POLIZZA);