INSERT INTO COSTO_POLIZZA_ETA (ETA_INIZIO,ETA_FINE, INCREMENTO, DT_INIZIO, DT_FINE) VALUES (14, 25, 100, TO_DATE('2023-01-01', 'YYYY-MM-DD'), NULL);
INSERT INTO COSTO_POLIZZA_ETA (ETA_INIZIO,ETA_FINE, INCREMENTO, DT_INIZIO, DT_FINE) VALUES (25, 30, 50, TO_DATE('2023-01-01', 'YYYY-MM-DD'), NULL);
INSERT INTO COSTO_POLIZZA_ETA (ETA_INIZIO,ETA_FINE, INCREMENTO, DT_INIZIO, DT_FINE) VALUES (30, 50, 0, TO_DATE('2023-01-01', 'YYYY-MM-DD'), NULL);
INSERT INTO COSTO_POLIZZA_ETA (ETA_INIZIO,ETA_FINE, INCREMENTO, DT_INIZIO, DT_FINE) VALUES (50, 60, 30, TO_DATE('2023-01-01', 'YYYY-MM-DD'), NULL);
INSERT INTO COSTO_POLIZZA_ETA (ETA_INIZIO,ETA_FINE, INCREMENTO, DT_INIZIO, DT_FINE) VALUES (60, 80, 50, TO_DATE('2023-01-01', 'YYYY-MM-DD'), NULL);
INSERT INTO COSTO_POLIZZA_ETA (ETA_INIZIO,ETA_FINE, INCREMENTO, DT_INIZIO, DT_FINE) VALUES (80, 200, 100, TO_DATE('2023-01-01', 'YYYY-MM-DD'), NULL);
